UPDATE NFE_XML SET NFE_INTEGRACAO = 'NFE'+CAST((SELECT NFE_ID FROM NFE_00 
WHERE 'NFE'+CAST(NFE_00.NFE_ID_OLD AS VARCHAR) = NFE_XML.NFE_INTEGRACAO_OLD AND NFE_00.COM_CODIGO = NFE_XML.COM_CODIGO) AS VARCHAR) 
WHERE (NFE_INTEGRACAO LIKE 'NFE%')
GO

UPDATE NFE_XML SET NFE_INTEGRACAO = 'OMF'+CAST((SELECT OMF_ID FROM OMF_00 
WHERE 'OMF'+CAST(OMF_00.OMF_ID_OLD AS VARCHAR) = NFE_XML.NFE_INTEGRACAO_OLD AND OMF_00.COM_CODIGO = NFE_XML.COM_CODIGO) AS VARCHAR) 
WHERE (NFE_INTEGRACAO LIKE 'OMF%')
GO