UPDATE OMF_00 SET OMF_INTEGRACAO = 'XML'+CAST((SELECT NFE_XML_ID FROM NFE_XML 
WHERE 'XML'+CAST(NFE_XML.NFE_XML_ID_OLD AS VARCHAR) = OMF_00.OMF_INTEGRACAO_OLD AND NFE_XML.COM_CODIGO = OMF_00.COM_CODIGO) AS VARCHAR) 
WHERE (OMF_INTEGRACAO LIKE 'XML%')
GO