UPDATE LFS_00 SET LFS_INTEGRACAO = 'FAT'+CAST((SELECT FAT_ID FROM FAT_00 
WHERE 'FAT'+CAST(FAT_00.FAT_ID_OLD AS VARCHAR) = LFS_00.LFS_INTEGRACAO_OLD AND FAT_00.COM_CODIGO = LFS_00.COM_CODIGO) AS VARCHAR) 
WHERE (LFS_INTEGRACAO LIKE 'FAT%')
GO

UPDATE LFS_00 SET LFS_INTEGRACAO = 'CTR'+CAST((SELECT CTR_ID FROM CTR_00 
WHERE 'CTR'+CAST(CTR_00.CTR_ID_OLD AS VARCHAR) = LFS_00.LFS_INTEGRACAO_OLD AND CTR_00.COM_CODIGO = LFS_00.COM_CODIGO) AS VARCHAR) 
WHERE (LFS_INTEGRACAO LIKE 'CTR%')
GO

UPDATE LFS_00 SET LFS_INTEGRACAO = 'OMF'+CAST((SELECT OMF_ID FROM OMF_00 
WHERE 'OMF'+CAST(OMF_00.OMF_ID_OLD AS VARCHAR) = LFS_00.LFS_INTEGRACAO_OLD AND OMF_00.COM_CODIGO = LFS_00.COM_CODIGO) AS VARCHAR) 
WHERE (LFS_INTEGRACAO LIKE 'OMF%')
GO