UPDATE CRE_00_02_01 SET CRE_INTEGRACAO = 'PCH'+CAST((SELECT PCH_ID FROM PCH_00 
WHERE 'PCH'+CAST(PCH_00.PCH_ID_OLD AS VARCHAR) = CRE_00_02_01.CRE_INTEGRACAO_OLD AND PCH_00.COM_CODIGO = CRE_00_02_01.COM_CODIGO) AS VARCHAR) 
WHERE (CRE_INTEGRACAO LIKE 'PCH%')
GO