UPDATE CRE_00_02_02 SET CRE_INTEGRACAO = 'DCH'+CAST((SELECT DCH_ID FROM DCH_00 
WHERE 'DCH'+CAST(DCH_00.DCH_ID_OLD AS VARCHAR) = CRE_00_02_02.CRE_INTEGRACAO_OLD AND DCH_00.COM_CODIGO = CRE_00_02_02.COM_CODIGO) AS VARCHAR) 
WHERE (CRE_INTEGRACAO LIKE 'DCH%')
GO