UPDATE XML_NFSE_00 SET XML_INTEGRACAO = 'LFS'+CAST((SELECT LFS_ID FROM LFS_00 
WHERE 'LFS'+CAST(LFS_00.LFS_ID_OLD AS VARCHAR) = XML_NFSE_00.XML_INTEGRACAO_OLD AND LFS_00.COM_CODIGO = XML_NFSE_00.COM_CODIGO) AS VARCHAR) 
WHERE (XML_INTEGRACAO LIKE 'LFS%')
GO