UPDATE REQ_00 SET REQ_INTEGRACAO = 'PPD'+CAST((SELECT PPD_ID FROM PPD_00 
WHERE 'PPD'+CAST(PPD_00.PPD_ID_OLD AS VARCHAR) = REQ_00.REQ_INTEGRACAO_OLD AND PPD_00.COM_CODIGO = REQ_00.COM_CODIGO) AS VARCHAR) 
WHERE (REQ_INTEGRACAO LIKE 'PPD%')
GO