UPDATE NFE_00 SET NFE_INTEGRACAO = 'XML'+CAST((SELECT NFE_XML_ID FROM NFE_XML 
WHERE 'XML'+CAST(NFE_XML.NFE_XML_ID_OLD AS VARCHAR) = NFE_00.NFE_INTEGRACAO_OLD AND NFE_XML.COM_CODIGO = NFE_00.COM_CODIGO) AS VARCHAR) 
WHERE (NFE_INTEGRACAO LIKE 'XML%')
GO