UPDATE CPA_00_01 SET CPA_INTEGRACAO = 'BCP'+CAST((SELECT BCP_ID FROM BCP_00 
WHERE 'BCP'+CAST(BCP_00.BCP_ID_OLD AS VARCHAR) = CPA_00_01.CPA_INTEGRACAO_OLD AND BCP_00.COM_CODIGO = CPA_00_01.COM_CODIGO) AS VARCHAR) 
WHERE (CPA_INTEGRACAO LIKE 'BCP%')
GO

UPDATE CPA_00_01 SET CPA_INTEGRACAO = 'BPI'+CAST((SELECT CPA_ID FROM CPA_00 T
WHERE 'BPI'+CAST(T.CPA_ID_OLD AS VARCHAR) = CPA_00_01.CPA_INTEGRACAO_OLD AND T.COM_CODIGO = CPA_00_01.COM_CODIGO) AS VARCHAR) 
WHERE (CPA_INTEGRACAO LIKE 'BPI%')
GO

UPDATE CPA_00_01 SET CPA_INTEGRACAO = 'MTL'+CAST((SELECT MTL_ID FROM MTL_00 
WHERE 'MTL'+CAST(MTL_00.MTL_ID_OLD AS VARCHAR) = CPA_00_01.CPA_INTEGRACAO_OLD AND MTL_00.COM_CODIGO = CPA_00_01.COM_CODIGO) AS VARCHAR) 
WHERE (CPA_INTEGRACAO LIKE 'MTL%')
GO