UPDATE CRB_00 SET CRB_INTEGRACAO = 'CTR'+CAST((SELECT CTR_ID FROM CTR_00 
WHERE 'CTR'+CAST(CTR_00.CTR_ID_OLD AS VARCHAR) = CRB_00.CRB_INTEGRACAO_OLD AND CTR_00.COM_CODIGO = CRB_00.COM_CODIGO) AS VARCHAR) 
WHERE (CRB_INTEGRACAO LIKE 'CTR%')
GO