UPDATE FCM_00 SET FCM_INTEGRACAO = 'CRE'+CAST((SELECT CRE_ID FROM CRE_00 
WHERE 'CRE'+CAST(CRE_00.CRE_ID_OLD AS VARCHAR) = FCM_00.FCM_INTEGRACAO_OLD AND CRE_00.COM_CODIGO = FCM_00.COM_CODIGO) AS VARCHAR) 
WHERE (FCM_INTEGRACAO LIKE 'CRE%')
GO

UPDATE FCM_00 SET FCM_INTEGRACAO = 'DEV'+CAST((SELECT DEV_ID FROM DEV_00 
WHERE 'DEV'+CAST(DEV_00.DEV_ID_OLD AS VARCHAR) = FCM_00.FCM_INTEGRACAO_OLD AND DEV_00.COM_CODIGO = FCM_00.COM_CODIGO) AS VARCHAR) 
WHERE (FCM_INTEGRACAO LIKE 'DEV%')
GO

UPDATE FCM_00 SET FCM_INTEGRACAO = 'FAT'+CAST((SELECT FAT_ID FROM FAT_00 
WHERE 'FAT'+CAST(FAT_00.FAT_ID_OLD AS VARCHAR) = FCM_00.FCM_INTEGRACAO_OLD AND FAT_00.COM_CODIGO = FCM_00.COM_CODIGO) AS VARCHAR) 
WHERE (FCM_INTEGRACAO LIKE 'FAT%')
GO