UPDATE CPA_00 SET CPA_INTEGRACAO = 'CPA'+CAST((SELECT CPA_ID FROM CPA_00 T
WHERE 'CPA'+CAST(T.CPA_ID_OLD AS VARCHAR) = CPA_00.CPA_INTEGRACAO_OLD AND T.COM_CODIGO = CPA_00.COM_CODIGO) AS VARCHAR) 
WHERE (CPA_INTEGRACAO LIKE 'CPA%')
GO

UPDATE CPA_00 SET CPA_INTEGRACAO = 'BPI'+CAST((SELECT CPA_ID FROM CPA_00 T
WHERE 'BPI'+CAST(T.CPA_ID_OLD AS VARCHAR) = CPA_00.CPA_INTEGRACAO_OLD AND T.COM_CODIGO = CPA_00.COM_CODIGO) AS VARCHAR) 
WHERE (CPA_INTEGRACAO LIKE 'BPI%')
GO

UPDATE CPA_00 SET CPA_INTEGRACAO = 'CRB'+CAST((SELECT CRB_ID FROM CRB_00 
WHERE 'CRB'+CAST(CRB_00.CRB_ID_OLD AS VARCHAR) = CPA_00.CPA_INTEGRACAO_OLD AND CRB_00.COM_CODIGO = CPA_00.COM_CODIGO) AS VARCHAR) 
WHERE (CPA_INTEGRACAO LIKE 'CRB%')
GO

UPDATE CPA_00 SET CPA_INTEGRACAO = 'MFC'+CAST((SELECT MFC_ID FROM MFC_00 
WHERE 'MFC'+CAST(MFC_00.MFC_ID_OLD AS VARCHAR) = CPA_00.CPA_INTEGRACAO_OLD AND MFC_00.COM_CODIGO = CPA_00.COM_CODIGO) AS VARCHAR) 
WHERE (CPA_INTEGRACAO LIKE 'MFC%')
GO

UPDATE CPA_00 SET CPA_INTEGRACAO = 'OMF'+CAST((SELECT OMF_ID FROM OMF_00 
WHERE 'OMF'+CAST(OMF_00.OMF_ID_OLD AS VARCHAR) = CPA_00.CPA_INTEGRACAO_OLD AND OMF_00.COM_CODIGO = CPA_00.COM_CODIGO) AS VARCHAR) 
WHERE (CPA_INTEGRACAO LIKE 'OMF%')
GO

UPDATE CPA_00 SET CPA_INTEGRACAO = 'RPA'+CAST((SELECT RPA_ID FROM RPA_00 
WHERE 'RPA'+CAST(RPA_00.RPA_ID_OLD AS VARCHAR) = CPA_00.CPA_INTEGRACAO_OLD AND RPA_00.COM_CODIGO = CPA_00.COM_CODIGO) AS VARCHAR) 
WHERE (CPA_INTEGRACAO LIKE 'RPA%')
GO

UPDATE CPA_00 SET CPA_INTEGRACAO = 'SCP'+CAST((SELECT SCP_ID FROM SCP_00 
WHERE 'SCP'+CAST(SCP_00.SCP_ID_OLD AS VARCHAR) = CPA_00.CPA_INTEGRACAO_OLD AND SCP_00.COM_CODIGO = CPA_00.COM_CODIGO) AS VARCHAR) 
WHERE (CPA_INTEGRACAO LIKE 'SCP%')
GO

UPDATE CPA_00 SET CPA_INTEGRACAO = 'NFE'+CAST((SELECT NFE_ID FROM NFE_00 
WHERE 'NFE'+CAST(NFE_00.NFE_ID_OLD AS VARCHAR) = CPA_00.CPA_INTEGRACAO_OLD AND NFE_00.COM_CODIGO = CPA_00.COM_CODIGO) AS VARCHAR) 
WHERE (CPA_INTEGRACAO LIKE 'NFE%')
GO