UPDATE FAT_00 SET FAT_INTEGRACAO = 'CGA'+CAST((SELECT CGA_ID FROM CGA_00 
WHERE 'CGA'+CAST(CGA_00.CGA_ID_OLD AS VARCHAR) = FAT_00.FAT_INTEGRACAO_OLD AND CGA_00.COM_CODIGO = FAT_00.COM_CODIGO) AS VARCHAR) 
WHERE (FAT_INTEGRACAO LIKE 'CGA%')
GO

UPDATE FAT_00 SET FAT_INTEGRACAO = 'CPS'+CAST((SELECT CPS_ID FROM CPS_00 
WHERE 'CPS'+CAST(CPS_00.CPS_ID_OLD AS VARCHAR) = FAT_00.FAT_INTEGRACAO_OLD AND CPS_00.COM_CODIGO = FAT_00.COM_CODIGO) AS VARCHAR) 
WHERE (FAT_INTEGRACAO LIKE 'CPS%')
GO

UPDATE FAT_00 SET FAT_INTEGRACAO = 'LIC'+CAST((SELECT LIC_ID FROM LIC_00 
WHERE 'LIC'+CAST(LIC_00.LIC_ID_OLD AS VARCHAR) = FAT_00.FAT_INTEGRACAO_OLD AND LIC_00.COM_CODIGO = FAT_00.COM_CODIGO) AS VARCHAR) 
WHERE (FAT_INTEGRACAO LIKE 'LIC%')
GO