UPDATE BCX_00 SET BCX_INTEGRACAO = 'AFC'+CAST((SELECT AFC_ID FROM AFC_00 
WHERE 'AFC'+CAST(AFC_00.AFC_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND AFC_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'AFC%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'BCC'+CAST((SELECT BCR_ID FROM BCR_00 
WHERE 'BCC'+CAST(BCR_00.BCR_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND BCR_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'BCC%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'BCR'+CAST((SELECT BCR_ID FROM BCR_00 
WHERE 'BCR'+CAST(BCR_00.BCR_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND BCR_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'BCR%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'BCI'+CAST((SELECT CRE_ID FROM CRE_00 
WHERE 'BCI'+CAST(CRE_00.CRE_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND CRE_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'BCI%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'ECI'+CAST((SELECT CRE_ID FROM CRE_00 
WHERE 'ECI'+CAST(CRE_00.CRE_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND CRE_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'ECI%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'BCP'+CAST((SELECT BCP_ID FROM BCP_00 
WHERE 'BCP'+CAST(BCP_00.BCP_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND BCP_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'BCP%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'BCX'+CAST((SELECT BCX_ID FROM BCX_00 T
WHERE 'BCX'+CAST(T.BCX_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND T.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'BCX%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'BPI'+CAST((SELECT CPA_ID FROM CPA_00 
WHERE 'BPI'+CAST(CPA_00.CPA_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND CPA_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'BPI%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'FAT'+CAST((SELECT FAT_ID FROM FAT_00 
WHERE 'FAT'+CAST(FAT_00.FAT_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND FAT_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'FAT%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'CRB'+CAST((SELECT CRB_ID FROM CRB_00 
WHERE 'CRB'+CAST(CRB_00.CRB_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND CRB_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'CRB%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'CTR'+CAST((SELECT CTR_ID FROM CTR_00 
WHERE 'CTR'+CAST(CTR_00.CTR_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND CTR_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'CTR%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'DCH'+CAST((SELECT DCH_ID FROM DCH_00 
WHERE 'DCH'+CAST(DCH_00.DCH_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND DCH_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'DCH%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'MTL'+CAST((SELECT MTL_ID FROM MTL_00 
WHERE 'MTL'+CAST(MTL_00.MTL_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND MTL_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'MTL%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'OMF'+CAST((SELECT OMF_ID FROM OMF_00 
WHERE 'OMF'+CAST(OMF_00.OMF_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND OMF_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'OMF%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'RFC'+CAST((SELECT RFC_ID FROM RFC_00 
WHERE 'RFC'+CAST(RFC_00.RFC_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND RFC_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'RFC%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'TLN'+CAST((SELECT TLN_ID FROM TLN_00 
WHERE 'TLN'+CAST(TLN_00.TLN_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND TLN_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'TLN%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'VEF'+CAST((SELECT VEF_ID FROM VEF_00 
WHERE 'VEF'+CAST(VEF_00.VEF_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND VEF_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'VEF%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'CPS'+CAST((SELECT CPS_ID FROM CPS_00 
WHERE 'CPS'+CAST(CPS_00.CPS_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND CPS_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'CPS%')
GO

UPDATE BCX_00 SET BCX_INTEGRACAO = 'ALG'+CAST((SELECT ALG_ID FROM ALG_00 
WHERE 'ALG'+CAST(ALG_00.ALG_ID_OLD AS VARCHAR) = BCX_00.BCX_INTEGRACAO_OLD AND ALG_00.COM_CODIGO = BCX_00.COM_CODIGO) AS VARCHAR) 
WHERE (BCX_INTEGRACAO LIKE 'ALG%')
GO