UPDATE CRE_00 SET CRE_INTEGRACAO = 'AFC'+CAST((SELECT AFC_ID FROM AFC_00 
WHERE 'AFC'+CAST(AFC_00.AFC_ID_OLD AS VARCHAR) = CRE_00.CRE_INTEGRACAO_OLD AND AFC_00.COM_CODIGO = CRE_00.COM_CODIGO) AS VARCHAR) 
WHERE (CRE_INTEGRACAO LIKE 'AFC%')
GO

UPDATE CRE_00 SET CRE_INTEGRACAO = 'BCI'+CAST((SELECT CRE_ID FROM CRE_00 T
WHERE 'BCI'+CAST(T.CRE_ID_OLD AS VARCHAR) = CRE_00.CRE_INTEGRACAO_OLD AND T.COM_CODIGO = CRE_00.COM_CODIGO) AS VARCHAR) 
WHERE (CRE_INTEGRACAO LIKE 'BCI%')
GO

UPDATE CRE_00 SET CRE_INTEGRACAO = 'FAT'+CAST((SELECT FAT_ID FROM FAT_00 
WHERE 'FAT'+CAST(FAT_00.FAT_ID_OLD AS VARCHAR) = CRE_00.CRE_INTEGRACAO_OLD AND FAT_00.COM_CODIGO = CRE_00.COM_CODIGO) AS VARCHAR) 
WHERE (CRE_INTEGRACAO LIKE 'FAT%')
GO

UPDATE CRE_00 SET CRE_INTEGRACAO = 'CRB'+CAST((SELECT CRB_ID FROM CRB_00 
WHERE 'CRB'+CAST(CRB_00.CRB_ID_OLD AS VARCHAR) = CRE_00.CRE_INTEGRACAO_OLD AND CRB_00.COM_CODIGO = CRE_00.COM_CODIGO) AS VARCHAR) 
WHERE (CRE_INTEGRACAO LIKE 'CRB%')
GO

UPDATE CRE_00 SET CRE_INTEGRACAO = 'LIC'+CAST((SELECT LIC_ID FROM LIC_00 
WHERE 'LIC'+CAST(LIC_00.LIC_ID_OLD AS VARCHAR) = CRE_00.CRE_INTEGRACAO_OLD AND LIC_00.COM_CODIGO = CRE_00.COM_CODIGO) AS VARCHAR) 
WHERE (CRE_INTEGRACAO LIKE 'LIC%')
GO

UPDATE CRE_00 SET CRE_INTEGRACAO = 'CTR'+CAST((SELECT CTR_ID FROM CTR_00 
WHERE 'CTR'+CAST(CTR_00.CTR_ID_OLD AS VARCHAR) = CRE_00.CRE_INTEGRACAO_OLD AND CTR_00.COM_CODIGO = CRE_00.COM_CODIGO) AS VARCHAR) 
WHERE (CRE_INTEGRACAO LIKE 'CTR%')
GO

UPDATE CRE_00 SET CRE_INTEGRACAO = 'OMF'+CAST((SELECT OMF_ID FROM OMF_00 
WHERE 'OMF'+CAST(OMF_00.OMF_ID_OLD AS VARCHAR) = CRE_00.CRE_INTEGRACAO_OLD AND OMF_00.COM_CODIGO = CRE_00.COM_CODIGO) AS VARCHAR) 
WHERE (CRE_INTEGRACAO LIKE 'OMF%')
GO

UPDATE CRE_00 SET CRE_INTEGRACAO = 'PCH'+CAST((SELECT PCH_ID FROM PCH_00 
WHERE 'PCH'+CAST(PCH_00.PCH_ID_OLD AS VARCHAR) = CRE_00.CRE_INTEGRACAO_OLD AND PCH_00.COM_CODIGO = CRE_00.COM_CODIGO) AS VARCHAR) 
WHERE (CRE_INTEGRACAO LIKE 'PCH%')
GO

UPDATE CRE_00 SET CRE_INTEGRACAO = 'RFC'+CAST((SELECT RFC_ID FROM RFC_00 
WHERE 'RFC'+CAST(RFC_00.RFC_ID_OLD AS VARCHAR) = CRE_00.CRE_INTEGRACAO_OLD AND RFC_00.COM_CODIGO = CRE_00.COM_CODIGO) AS VARCHAR) 
WHERE (CRE_INTEGRACAO LIKE 'RFC%')
GO

UPDATE CRE_00 SET CRE_INTEGRACAO = 'SCR'+CAST((SELECT SCR_ID FROM SCR_00 
WHERE 'SCR'+CAST(SCR_00.SCR_ID_OLD AS VARCHAR) = CRE_00.CRE_INTEGRACAO_OLD AND SCR_00.COM_CODIGO = CRE_00.COM_CODIGO) AS VARCHAR) 
WHERE (CRE_INTEGRACAO LIKE 'SCR%')
GO

UPDATE CRE_00 SET CRE_INTEGRACAO = 'SCT'+CAST((SELECT SCT_ID FROM SCT_00 
WHERE 'SCT'+CAST(SCT_00.SCT_ID_OLD AS VARCHAR) = CRE_00.CRE_INTEGRACAO_OLD AND SCT_00.COM_CODIGO = CRE_00.COM_CODIGO) AS VARCHAR) 
WHERE (CRE_INTEGRACAO LIKE 'SCT%')
GO

UPDATE CRE_00 SET CRE_INTEGRACAO = 'VEF'+CAST((SELECT VEF_ID FROM VEF_00 
WHERE 'VEF'+CAST(VEF_00.VEF_ID_OLD AS VARCHAR) = CRE_00.CRE_INTEGRACAO_OLD AND VEF_00.COM_CODIGO = CRE_00.COM_CODIGO) AS VARCHAR) 
WHERE (CRE_INTEGRACAO LIKE 'VEF%')
GO

UPDATE CRE_00 SET CRE_INTEGRACAO = 'CPS'+CAST((SELECT CPS_ID FROM CPS_00 
WHERE 'CPS'+CAST(CPS_00.CPS_ID_OLD AS VARCHAR) = CRE_00.CRE_INTEGRACAO_OLD AND CPS_00.COM_CODIGO = CRE_00.COM_CODIGO) AS VARCHAR) 
WHERE (CRE_INTEGRACAO LIKE 'CPS%')
GO

UPDATE CRE_00 SET CRE_INTEGRACAO = 'ALG'+CAST((SELECT ALG_ID FROM ALG_00 
WHERE 'ALG'+CAST(ALG_00.ALG_ID_OLD AS VARCHAR) = CRE_00.CRE_INTEGRACAO_OLD AND ALG_00.COM_CODIGO = CRE_00.COM_CODIGO) AS VARCHAR) 
WHERE (CRE_INTEGRACAO LIKE 'ALG%')
GO