 -- "Lin2110" Criando campo [ONS_ID_OLD] pra receber IDs do campo [ONS_ID] PARA GUARDAR OS IDs ANTIGOS 
 IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE COLUMNS.TABLE_NAME = 'CMD_00_01'
 AND COLUMNS.COLUMN_NAME = 'ONS_ID_OLD')
 BEGIN 
 ALTER TABLE dbo.CMD_00_01
 ADD ONS_ID_OLD int NULL 
 END; 
 GO 
  
 -- "Lin2122" Guarda [ONS_ID] de relação com  [ONS_ID_OLD] 
 UPDATE CMD_00_01
 SET    ONS_ID_OLD = ONS_ID
 WHERE  ONS_ID_OLD IS NULL 
 GO 

 -- Atualiza novos ids tabela [ONS_00] campo [ONS_ID], na table filha [SCP_00_01] campo [CPA_ID] 
 UPDATE CMD_00_01 -- FILHA 
 SET CMD_00_01.ONS_ID = SUBSTRING(T2.OMF_INTEGRACAO, 4, 17) -- FILHA  RECEBE DA MÃE 
 FROM CMD_00_01 -- FILHA 
 INNER JOIN OMF_00 T2 ON (CMD_00_01.ONS_ID_OLD = SUBSTRING(T2.OMF_INTEGRACAO, 4, 17)) 
 AND (CMD_00_01.COM_CODIGO    = T2.COM_CODIGO)  --RELACIONA FILHA COM MAE
 AND (SUBSTRING(T2.OMF_INTEGRACAO, 1, 3) = 'ONS') 
 GO 

 -- "Lin2110" Criando campo [ONS_01_ID_OLD] pra receber IDs do campo [ONS_01_ID] PARA GUARDAR OS IDs ANTIGOS 
 IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE COLUMNS.TABLE_NAME = 'CMD_00_01'
 AND COLUMNS.COLUMN_NAME = 'ONS_01_ID_OLD')
 BEGIN 
 ALTER TABLE dbo.CMD_00_01
 ADD ONS_01_ID_OLD int NULL 
 END; 
 GO 
  
 -- "Lin2122" Guarda [ONS_01_ID] de relação com  [ONS_01_ID_OLD] 
 UPDATE CMD_00_01
 SET    ONS_01_ID_OLD = ONS_01_ID
 WHERE  ONS_01_ID_OLD IS NULL 
 GO 

 -- Atualiza novos ids tabela [ONS_00] campo [ONS_ID], na table filha [SCP_00_01] campo [CPA_ID] 
 UPDATE CMD_00_01 -- FILHA 
 SET CMD_00_01.ONS_01_ID = SUBSTRING(T2.OMF_INTEGRACAOERP, 4, 17) -- FILHA  RECEBE DA MÃE 
 FROM CMD_00_01 -- FILHA 
 INNER JOIN OMF_00_01 T2 ON (CMD_00_01.ONS_01_ID_OLD = SUBSTRING(T2.OMF_INTEGRACAOERP, 4, 17)) 
 AND (CMD_00_01.COM_CODIGO    = T2.COM_CODIGO)  --RELACIONA FILHA COM MAE
 AND (SUBSTRING(T2.OMF_INTEGRACAOERP, 1, 3) = 'ONS') 
 GO