 -- "Lin2110" Criando campo [LIB_ID_OLD] pra receber IDs do campo [LIB_ID] PARA GUARDAR OS IDs ANTIGOS 
 IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE COLUMNS.TABLE_NAME = 'VEF_00'
 AND COLUMNS.COLUMN_NAME = 'LIB_ID_OLD')
 BEGIN 
 ALTER TABLE dbo.VEF_00
 ADD LIB_ID_OLD int NULL 
 END; 
 GO 
  
 -- "Lin2122" Guarda [LIB_ID] de relação com  [LIB_ID_OLD] 
 UPDATE VEF_00
 SET    LIB_ID_OLD = LIB_ID
 WHERE  LIB_ID_OLD IS NULL 
 GO

 -- Atualiza novos ids tabela [LIB_00] campo [LIB_ID], na table filha [SCP_00_01] campo [CPA_ID] 
 UPDATE VEF_00 -- FILHA 
 SET VEF_00.LIB_ID = T2.LIB_ID -- FILHA  RECEBE DA MÃE 
 FROM VEF_00 -- FILHA 
 INNER JOIN LIB_00 T2 ON (VEF_00.LIB_ID_OLD = T2.LIB_ID_OLD) 
 AND (VEF_00.COM_CODIGO    = T2.COM_CODIGO)  --RELACIONA FILHA COM MAE 
 GO
