 -- "Lin2110" Criando campo [CMP_ID_OLD] pra receber IDs do campo [CMP_ID] PARA GUARDAR OS IDs ANTIGOS 
 IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE COLUMNS.TABLE_NAME = 'NFE_00_01'
 AND COLUMNS.COLUMN_NAME = 'CMP_ID_OLD')
 BEGIN 
 ALTER TABLE dbo.NFE_00_01
 ADD CMP_ID_OLD int NULL 
 END; 
 GO 
  
 -- "Lin2122" Guarda [CMP_ID] de relação com  [CMP_ID_OLD] 
 UPDATE NFE_00_01
 SET    CMP_ID_OLD = CMP_ID
 WHERE  CMP_ID_OLD IS NULL 
 GO

 -- Atualiza novos ids tabela [CMP_00] campo [CMP_ID], na table filha [SCP_00_01] campo [CPA_ID] 
 UPDATE NFE_00_01 -- FILHA 
 SET NFE_00_01.CMP_ID = T2.CMP_ID -- FILHA  RECEBE DA MÃE 
 FROM NFE_00_01 -- FILHA 
 INNER JOIN CMP_00 T2 ON (NFE_00_01.CMP_ID_OLD = T2.CMP_ID_OLD) 
 AND (NFE_00_01.COM_CODIGO    = T2.COM_CODIGO)  --RELACIONA FILHA COM MAE 
 GO
