 -- "Lin2110" Criando campo [TLN_ID_OLD] pra receber IDs do campo [TLN_ID] PARA GUARDAR OS IDs ANTIGOS 
 IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE COLUMNS.TABLE_NAME = 'CPA_00_01'
 AND COLUMNS.COLUMN_NAME = 'TLN_ID_OLD')
 BEGIN 
 ALTER TABLE dbo.CPA_00_01
 ADD TLN_ID_OLD int NULL 
 END; 
 GO 
  
 -- "Lin2122" Guarda [TLN_ID] de relação com  [TLN_ID_OLD] 
 UPDATE CPA_00_01
 SET    TLN_ID_OLD = TLN_ID
 WHERE  TLN_ID_OLD IS NULL 
 GO

 -- Atualiza novos ids tabela [TLN_00] campo [TLN_ID], na table filha [SCP_00_01] campo [CPA_ID] 
 UPDATE CPA_00_01 -- FILHA 
 SET CPA_00_01.TLN_ID = T2.TLN_ID -- FILHA  RECEBE DA MÃE 
 FROM CPA_00_01 -- FILHA 
 INNER JOIN TLN_00 T2 ON (CPA_00_01.TLN_ID_OLD = T2.TLN_ID_OLD) 
 AND (CPA_00_01.COM_CODIGO    = T2.COM_CODIGO)  --RELACIONA FILHA COM MAE 
 GO 
