 -- "Lin2110" Criando campo [PDA_ID_OLD] pra receber IDs do campo [PDA_ID] PARA GUARDAR OS IDs ANTIGOS 
 IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE COLUMNS.TABLE_NAME = 'CGA_00_01'
 AND COLUMNS.COLUMN_NAME = 'PDA_ID_OLD')
 BEGIN 
 ALTER TABLE dbo.CGA_00_01
 ADD PDA_ID_OLD int NULL 
 END; 
 GO
 
 -- "Lin2122" Guarda [PDA_ID] de relação com  [PDA_ID_OLD] 
 UPDATE CGA_00_01
 SET    PDA_ID_OLD = PDA_ID
 WHERE  PDA_ID_OLD IS NULL 
 GO

 UPDATE CGA_00_01
 SET CGA_00_01.FAT_ID = T2.FAT_ID
 FROM CGA_00_01
 INNER JOIN FAT_00 T2 ON (CGA_00_01.CGA_ID = T2.CGA_ID) 
 AND (CGA_00_01.PDA_ID = T2.PDA_ID) 
 AND (CGA_00_01.COM_CODIGO = T2.COM_CODIGO)
 GO