 -- "Lin2110" Criando campo [NFE_ID_OLD] pra receber IDs do campo [NFE_ID] PARA GUARDAR OS IDs ANTIGOS 
 IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE COLUMNS.TABLE_NAME = 'MEG_00'
 AND COLUMNS.COLUMN_NAME = 'NFE_ID_OLD')
 BEGIN 
 ALTER TABLE dbo.MEG_00
 ADD NFE_ID_OLD int NULL 
 END; 
 GO 
  
 -- "Lin2122" Guarda [NFE_ID] de relação com  [NFE_ID_OLD] 
 UPDATE MEG_00
 SET    NFE_ID_OLD = NFE_ID
 WHERE  NFE_ID_OLD IS NULL 
 GO

 -- Atualiza novos ids tabela [NFE_00] campo [NFE_ID], na table filha [SCP_00_01] campo [CPA_ID] 
 UPDATE MEG_00 -- FILHA 
 SET MEG_00.NFE_ID = T2.NFE_ID -- FILHA  RECEBE DA MÃE 
 FROM MEG_00 -- FILHA 
 INNER JOIN NFE_00 T2 ON (MEG_00.NFE_ID_OLD = T2.NFE_ID_OLD) 
 AND (MEG_00.COM_CODIGO    = T2.COM_CODIGO)  --RELACIONA FILHA COM MAE 
 GO