 -- "Lin2110" Criando campo [LFS_ID_OLD] pra receber IDs do campo [LFS_ID] PARA GUARDAR OS IDs ANTIGOS 
 IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE COLUMNS.TABLE_NAME = 'MFC_00_04'
 AND COLUMNS.COLUMN_NAME = 'LFS_ID_OLD')
 BEGIN 
 ALTER TABLE dbo.MFC_00_04
 ADD LFS_ID_OLD int NULL 
 END; 
 GO 
  
 -- "Lin2122" Guarda [LFS_ID] de relação com  [LFS_ID_OLD] 
 UPDATE MFC_00_04
 SET    LFS_ID_OLD = LFS_ID
 WHERE  LFS_ID_OLD IS NULL 
 GO

 -- Atualiza novos ids tabela [LFS_00] campo [LFS_ID], na table filha [SCP_00_01] campo [CPA_ID] 
 UPDATE MFC_00_04 -- FILHA 
 SET MFC_00_04.LFS_ID = T2.LFS_ID -- FILHA  RECEBE DA MÃE 
 FROM MFC_00_04 -- FILHA 
 INNER JOIN LFS_00 T2 ON (MFC_00_04.LFS_ID_OLD = T2.LFS_ID_OLD) 
 AND (MFC_00_04.COM_CODIGO    = T2.COM_CODIGO)  --RELACIONA FILHA COM MAE 
 GO
