 IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE COLUMNS.TABLE_NAME = 'OMF_00_01'
 AND COLUMNS.COLUMN_NAME = 'FAT_ID_OLD')
 BEGIN 
 ALTER TABLE dbo.OMF_00_01
 ADD FAT_ID_OLD int NULL 
 END; 
 GO 

 IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE COLUMNS.TABLE_NAME = 'OMF_00_01'
 AND COLUMNS.COLUMN_NAME = 'FAT_01_ID_OLD')
 BEGIN 
 ALTER TABLE dbo.OMF_00_01
 ADD FAT_01_ID_OLD int NULL 
 END; 
 GO
  
 UPDATE OMF_00_01
 SET    FAT_ID_OLD = FAT_ID
 WHERE  FAT_ID_OLD IS NULL 
 GO

 UPDATE OMF_00_01
 SET    FAT_01_ID_OLD = FAT_01_ID
 WHERE  FAT_01_ID_OLD IS NULL 
 GO 

 UPDATE OMF_00_01 -- FILHA 
 SET OMF_00_01.FAT_ID = T2.FAT_ID -- FILHA  RECEBE DA MÃE 
 FROM OMF_00_01 -- FILHA 
 INNER JOIN FAT_00 T2 ON (OMF_00_01.FAT_ID_OLD = T2.FAT_ID_OLD) 
 AND (OMF_00_01.COM_CODIGO    = T2.COM_CODIGO)  --RELACIONA FILHA COM MAE 
 GO

 UPDATE OMF_00_01 -- FILHA 
 SET OMF_00_01.FAT_01_ID = T2.FAT_01_ID -- FILHA  RECEBE DA MÃE 
 FROM OMF_00_01 -- FILHA 
 INNER JOIN FAT_00_01 T2 ON (OMF_00_01.FAT_01_ID_OLD = T2.FAT_01_ID_OLD) 
 AND (OMF_00_01.COM_CODIGO    = T2.COM_CODIGO)  --RELACIONA FILHA COM MAE 
 GO