 -- "Lin2110" Criando campo [CLT_ID_OLD] pra receber IDs do campo [CLT_ID] PARA GUARDAR OS IDs ANTIGOS 
 IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE COLUMNS.TABLE_NAME = 'CTR_00_01'
 AND COLUMNS.COLUMN_NAME = 'CLT_ID_OLD')
 BEGIN 
 ALTER TABLE dbo.CTR_00_01
 ADD CLT_ID_OLD int NULL 
 END; 
 GO 
  
 -- "Lin2122" Guarda [CLT_ID] de relação com  [CLT_ID_OLD] 
 UPDATE CTR_00_01
 SET    CLT_ID_OLD = CLT_ID
 WHERE  CLT_ID_OLD IS NULL 
 GO

 -- Atualiza novos ids tabela [CLT_00] campo [CLT_ID], na table filha [SCP_00_01] campo [CPA_ID] 
 UPDATE CTR_00_01 -- FILHA 
 SET CTR_00_01.CLT_ID = T2.CLT_ID -- FILHA  RECEBE DA MÃE 
 FROM CTR_00_01 -- FILHA 
 INNER JOIN CLT_00 T2 ON (CTR_00_01.CLT_ID_OLD = T2.CLT_ID_OLD) 
 AND (CTR_00_01.COM_CODIGO    = T2.COM_CODIGO)  --RELACIONA FILHA COM MAE 
 GO 
