 -- "Lin2110" Criando campo [CRE_ID_OLD] pra receber IDs do campo [CRE_ID] PARA GUARDAR OS IDs ANTIGOS 
 IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE COLUMNS.TABLE_NAME = 'BCP_00_01'
 AND COLUMNS.COLUMN_NAME = 'CRE_ID_OLD')
 BEGIN 
 ALTER TABLE dbo.BCP_00_01
 ADD CRE_ID_OLD int NULL 
 END; 
 GO 
  
 -- "Lin2122" Guarda [CRE_ID] de relação com  [CRE_ID_OLD] 
 UPDATE BCP_00_01
 SET    CRE_ID_OLD = CRE_ID
 WHERE  CRE_ID_OLD IS NULL 
 GO

 -- Atualiza novos ids tabela [CRE_00] campo [CRE_ID], na table filha [SCP_00_01] campo [CPA_ID] 
 UPDATE BCP_00_01 -- FILHA 
 SET BCP_00_01.CRE_ID = T2.CRE_ID -- FILHA  RECEBE DA MÃE 
 FROM BCP_00_01 -- FILHA 
 INNER JOIN CRE_00 T2 ON (BCP_00_01.CRE_ID_OLD = T2.CRE_ID_OLD) 
 AND (BCP_00_01.COM_CODIGO    = T2.COM_CODIGO)  --RELACIONA FILHA COM MAE 
 GO 
