 -- "Lin2110" Criando campo [CGA_ID_OLD] pra receber IDs do campo [CGA_ID] PARA GUARDAR OS IDs ANTIGOS 
 IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE COLUMNS.TABLE_NAME = 'GNRE_00'
 AND COLUMNS.COLUMN_NAME = 'CGA_ID_OLD')
 BEGIN 
 ALTER TABLE dbo.GNRE_00
 ADD CGA_ID_OLD int NULL 
 END; 
 GO 
  
 -- "Lin2122" Guarda [CGA_ID] de relação com  [CGA_ID_OLD] 
 UPDATE GNRE_00
 SET    CGA_ID_OLD = CGA_ID
 WHERE  CGA_ID_OLD IS NULL 
 GO

 -- Atualiza novos ids tabela [CGA_00] campo [CGA_ID], na table filha [SCP_00_01] campo [CPA_ID] 
 UPDATE GNRE_00 -- FILHA 
 SET GNRE_00.CGA_ID = T2.CGA_ID -- FILHA  RECEBE DA MÃE 
 FROM GNRE_00 -- FILHA 
 INNER JOIN CGA_00 T2 ON (GNRE_00.CGA_ID_OLD = T2.CGA_ID_OLD) 
 AND (GNRE_00.COM_CODIGO    = T2.COM_CODIGO)  --RELACIONA FILHA COM MAE 
 GO