 -- "Lin2110" Criando campo [CPA_ID_OLD] pra receber IDs do campo [CPA_ID] PARA GUARDAR OS IDs ANTIGOS 
 IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE COLUMNS.TABLE_NAME = 'BCX_00'
 AND COLUMNS.COLUMN_NAME = 'CPA_ID_OLD')
 BEGIN 
 ALTER TABLE dbo.BCX_00
 ADD CPA_ID_OLD int NULL 
 END; 
 GO 
  
 -- "Lin2122" Guarda [CPA_ID] de relação com  [CPA_ID_OLD] 
 UPDATE BCX_00
 SET    CPA_ID_OLD = CPA_ID
 WHERE  CPA_ID_OLD IS NULL 
 GO

 -- Atualiza novos ids tabela [CPA_00] campo [CPA_ID], na table filha [SCP_00_01] campo [CPA_ID] 
 UPDATE BCX_00 -- FILHA 
 SET BCX_00.CPA_ID = T2.CPA_ID -- FILHA  RECEBE DA MÃE 
 FROM BCX_00 -- FILHA 
 INNER JOIN CPA_00 T2 ON (BCX_00.CPA_ID_OLD = T2.CPA_ID_OLD) 
 AND (BCX_00.COM_CODIGO    = T2.COM_CODIGO)  --RELACIONA FILHA COM MAE 
 GO 
  
 -- "Lin2110" Criando campo [CRE_ID_OLD] pra receber IDs do campo [CRE_ID] PARA GUARDAR OS IDs ANTIGOS 
 IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE COLUMNS.TABLE_NAME = 'BCX_00'
 AND COLUMNS.COLUMN_NAME = 'CRE_ID_OLD')
 BEGIN 
 ALTER TABLE dbo.BCX_00
 ADD CRE_ID_OLD int NULL 
 END; 
 GO 
  
 -- "Lin2122" Guarda [CRE_ID] de relação com  [CRE_ID_OLD] 
 UPDATE BCX_00
 SET    CRE_ID_OLD = CRE_ID
 WHERE  CRE_ID_OLD IS NULL 
 GO 
 
 -- Atualiza novos ids tabela [CRE_00] campo [CRE_ID], na table filha [SCP_00_01] campo [CPA_ID] 
 UPDATE BCX_00 -- FILHA 
 SET BCX_00.CRE_ID = T2.CRE_ID -- FILHA  RECEBE DA MÃE 
 FROM BCX_00 -- FILHA 
 INNER JOIN CRE_00 T2 ON (BCX_00.CRE_ID_OLD = T2.CRE_ID_OLD) 
 AND (BCX_00.COM_CODIGO    = T2.COM_CODIGO)  --RELACIONA FILHA COM MAE 
 GO